### PR TITLE
improve FB classes

### PR DESCRIPTION
**Pull request by junchaoxia**
improve the FB classes by calling the base constructor (fix issue  #13) and separating a build function for the constructor (fix issue #17).

### CODE REVIEW

**Comment by vineetbansal** [comment]
In comparing the _build methods of the 2 classes:

screenshot

It seems to me that they're doing exactly the same thing, except for the calculation of `basis_count`.

I'd propose the following:

1. Move the `_build` up the hierarchy, and call it as the last step of the constructor. Make clear in the documentation that the subclasses need to supply the `indices`, `precomp` and `norms` methods (and what exactly they populate in the class). Where the comments say `2d` of `3d`, just say `N-d`.

However, since you need `basis_count` in the `indices/precomp/norms` methods, you may have to implement a `_compute_basis_count()` or similar method that the base `__init__` calls at the appropriate place, and the subclasses implement independently.

(1) above is a suggestion. If you find that the new *fast-fb-basis* class you're working on has a drastically different `_build` that cannot take advantage of any of this infrastructure, then we're fine duplicating code across the 2 current `_build` methods. However, in that case, the following suggestions still apply:

2. There's a `dtype=int` in one `_build` but not the other (also check pep8 on this one). Since k_max is supposed to hold the no. of zeros, I'd think both of them should have `dtype=int`.

3. Why have local variables like `basis_count` and `basis_coords` if they're only ever going to be used once in the very next line:

```
        basis_count = k_max[0] + sum(2 * k_max[1:])
        self.basis_count = basis_count
```

could just be
```
        self.basis_count = k_max[0] + sum(2 * k_max[1:])
```

Savings like this can reduce code size over time.

4. We should have a `unique_coords_Nd` function in `basis_func.py` with a new `ndim` argument (2 or 3), which calls `unique_coords_2d` or `unique_coords_3d` internally. Then the common `_build` method could just call `unique_coords_Nd(self.d, ...` etc. This should be the case even if there is no common `_build` method.

5. Looks to me like the `Basis` class shouldn't be doing this:

```
        ensure(d in (2, 3), 'Only two- or three-dimensional basis functions are supported.')
        ensure(len(set(size)) == 1, 'Only square and cubic domains are supported.')
```

Since it's none of it's business - just let the subclasses do any enforcement on `d` (like you're doing now).

**Comment by junchaoxia** [comment]
The build function should be quite different for PSWF which we need to merge later. So it can not be moved to the topest level but we can introduce a  derived class called FB in the middle to define the common functions from both the FB2D and FB3D if we think it is not too deep.  I am trying to derive the fast FBs from the corresponding standard FBs so the build functions are not defined again in the fast versions.  Depending on how we will organize all of them, there should be more tweaking. I will make other small adjustments.

**Comment by janden** [comment]
> 1. Move the _build up the hierarchy, and call it as the last step of the constructor. Make clear in the documentation that the subclasses need to supply the indices, precomp and norms methods (and what exactly they populate in the class). Where the comments say 2d of 3d, just say N-d.

I agree, but, as @junchaoxia says, these things are not common to all basis objects, only to the FB basis. In particular PSWF basis will have a different `_build()` (although it will have some similarities, but we will look at that when we come to it), so it would make sense to have a FBBasis superclass that takes care of the common parts (including `_build()`).

I'm also thinking `_build()` should be public (i.e., `build()`). The reason for the function is allow it to "rebuild" if we change the parameters (e.g., `ell_max` or something else), so it should be callable by the user. On the other hand, I think this is a very unlikely scenario, so let's keep it private for now.

> 4. ... 5.

Yes. I agree.

**Comment by junchaoxia** [comment]
I push back the corresponding changes for all comments listed. To reduce the size of build function for each derived class, a common function to get FB zeros is moved to base class although it  should be different for PSWF. Namely we will have a separate function for PSWF.

**Comment by vineetbansal** [comment]
looks like some tests are still relying on `unique_coords_2d` and `unique_coords_3d`, which are now failing on Travis.

**Comment by junchaoxia** [comment]
Pycharm could not catch all name changes to `unique_coords_2d` . I also remove some duplicate unit tests for the Bessel function.

**Pull request merged**
